//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatNow.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlOption()
        {
            this.ControlLogs = new HashSet<ControlLog>();
            this.LogPresets = new HashSet<LogPreset>();
        }
    
        public int Id { get; set; }
        public int ControlId { get; set; }
        public string Name { get; set; }
        public string FunnyName { get; set; }
    
        public virtual Control Control { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlLog> ControlLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPreset> LogPresets { get; set; }
    }
}
