//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatNow.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlLog
    {
        public int Id { get; set; }
        public int LogId { get; set; }
        public int ControlId { get; set; }
        public Nullable<int> ControlOptionId { get; set; }
        public string Value { get; set; }
    
        public virtual Control Control { get; set; }
        public virtual ControlOption ControlOption { get; set; }
        public virtual Log Log { get; set; }
    }
}
