//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatNow.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLogOption
    {
        public int Id { get; set; }
        public int ItemLogId { get; set; }
        public int ItemOptionId { get; set; }
        public string Value { get; set; }
    
        public virtual ItemLog ItemLog { get; set; }
        public virtual ItemOption ItemOption { get; set; }
    }
}
