//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatNow.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDetail
    {
        public int LogId { get; set; }
        public int ControlLogId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Logged { get; set; }
        public string Item { get; set; }
        public string Control { get; set; }
        public string Value { get; set; }
    }
}
