//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatNow.Data.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPresetDetail
    {
        public int Id { get; set; }
        public int ItemPresetId { get; set; }
        public int ItemId { get; set; }
        public int LogGroup { get; set; }
        public int ControlId { get; set; }
        public Nullable<int> ControlOptionId { get; set; }
        public string Value { get; set; }
    }
}
